# -*- coding: utf-8 -*-
"""Calculadora2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhh6Smt0k4t4AjDBfoz9gg6aQnz_Wdw3
"""

def calculadora():
    print("Calculadora Python Simples")
    print("Operações disponíveis:")
    print("1. Adição (+)")
    print("2. Subtração (-)")
    print("3. Multiplicação (*)")
    print("4. Divisão (/)")
    print("5. Sair")

    while True:
        escolha = input("\nEscolha a operação (1-5): ")

        if escolha == '5':
            print("Calculadora encerrada.")
            break

        if escolha not in ['1', '2', '3', '4']:
            print("Opção inválida. Tente novamente.")
            continue

        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))

        if escolha == '1':
            print(f"Resultado: {num1} + {num2} = {num1 + num2}")
        elif escolha == '2':
            print(f"Resultado: {num1} - {num2} = {num1 - num2}")
        elif escolha == '3':
            print(f"Resultado: {num1} * {num2} = {num1 * num2}")
        elif escolha == '4':
            if num2 == 0:
                print("Erro! Divisão por zero não é permitida.")
            else:
                print(f"Resultado: {num1} / {num2} = {num1 / num2}")

if __name__ == "__main__":
    calculadora()